name: acehornweb
description: "Sitio web oficial del artista ACEHORN (EDM)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # √çconos estilo iOS
  cupertino_icons: ^1.0.8
  fluro: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#  assets:
  #  - assets/images/
  #  - assets/fonts/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Old London
      fonts:
        - asset: assets/fonts/OldLondon.ttf
          weight: 600
